import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'framework/index': 'src/framework/index.ts',
    'framework/api': 'src/framework/api.ts',
    'adapters/VercelAIProvider': 'src/adapters/VercelAIProvider.ts',
    'core/types': 'src/core/types.ts',
    'core/type-helpers': 'src/core/type-helpers.ts',
    'core/BaseAgent': 'src/core/BaseAgent.ts',
    'core/CostCalculator': 'src/core/CostCalculator.ts',
    'core/version': 'src/core/version.ts',
    'agents/index': 'src/agents/index.ts',
    'mesh/index': 'src/mesh/index.ts',
    'mesh/types': 'src/mesh/types.ts',
    'mesh/MeshAgent': 'src/mesh/MeshAgent.ts',
    'mesh/MeshCoordinator': 'src/mesh/MeshCoordinator.ts',
    'mesh/PerformanceMonitor': 'src/mesh/PerformanceMonitor.ts',
    'mesh/SimpleCache': 'src/mesh/SimpleCache.ts',
    'registry/index': 'src/registry/index.ts',
    'schemas/nutrition.schema': 'src/schemas/nutrition.schema.ts',
    'schemas/workout.schema': 'src/schemas/workout.schema.ts',
    'utils/ai-agent-setup': 'src/utils/ai-agent-setup.ts',
    'sdk-agents/copilot/index': 'src/sdk-agents/copilot/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: false,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'node18',
  external: [
    /^@giulio-leone\/.*/,
    /^@onecoach\/.*/,
    '@prisma/client',
    '@ai-sdk/anthropic',
    '@ai-sdk/openai',
    '@modelcontextprotocol/sdk',
    '@openrouter/ai-sdk-provider',
    /^@workflow\/.*/,
    'ai',
    'yaml',
    'zod',
  ],
});
